# Main site info
author: Juliana Rizzo
url: "https://www.jrizzo.me"
site_name: Juliana Rizzo
site_description: Microbiologist, watercolorist, photographer, fungi-lover
brand: JULIANA RIZZO
language: en
keywords: 'science, microbiologist, fungi, cryptococcus'
repository: lucasbalancin/website
repository_branch: main
favicon: images/favicon-32x32.png
thumbnail: images/thumbnail/default.png
license_notice: |
  Except where noted, all content is licensed
  <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a>

# Social media
twitter: julianarizzophd
linkedin: https://www.linkedin.com/in/juliana-rizzo/
orcid: 0000-0001-5538-6471
researchgate: https://www.researchgate.net/profile/Juliana-Rizzo
googlescholar: https://scholar.google.com.ar/citations?user=Of1hwrAAAAAJ
pubmed: https://pubmed.ncbi.nlm.nih.gov/?term=(Juliana+Rizzo[Author])

# Menu
navigation:
  - name: Home
    id: index
  - name: About
    id: about/index


# Don't copy or process these files
ignore:
  - README.md
  - LICENSE.md
  - environment.yml
  - Makefile
  - css/academicons/README.md
